"""V1.1-C DataCo event mapping: ORDER_CREATED / SHIPMENT_RECORDED /
DELIVERY_STATUS_RECORDED.

Deterministic, frozen mapping of governed DataCo columns to per-order events:

- ORDER_CREATED          <- order date (DateOrders), timestamp canonical UTC
- SHIPMENT_RECORDED      <- shipping date (DateOrders), timestamp canonical UTC
- DELIVERY_STATUS_RECORDED <- observed Delivery Status value; timestamp reuses
  the last governed timestamp (shipping date) because the dataset has no
  delivery/label timestamp column (no invented timestamps; equal timestamps
  ordered by the frozen event sequence).

payload_ref is left null: V1.1-C persists digests only (DIGEST_MINIMAL_METADATA),
the authoritative canonical payload archive is a later-stage concern.

AI_RISK_ASSESSED is NEVER generated by V1.1-C.
"""

from __future__ import annotations

from typing import Any, Mapping

from src.blockchain_engine.canonical import sha256_hex

from .dataco_schema import (
    DELIVERY_STATUS_COLUMN,
    ORDER_STATUS_COLUMN,
    DataCoSchemaError,
    canonical_timestamp,
)
from .order_aggregation import order_aggregate_digest


def _observed_or_sentinel(row: Mapping[str, Any], column: str) -> str:
    value = row.get(column)
    if value is None or (isinstance(value, str) and not value.strip()):
        raise DataCoSchemaError(
            f"missing required observed attribute {column!r} for order"
        )
    return str(value).strip()


def build_mapping_events(
    order_rows: list[Mapping[str, Any]],
    *,
    aggregate: Mapping[str, Any],
    order_creation_canonical: str,
    shipment_canonical: str,
) -> list[dict[str, Any]]:
    """Build the V1.1-C event plan (payload digests) for one order.

    Each item records ``event_type``, ``event_timestamp``, and ``payload_digest``
    exactly as they will be appended to the order's chain. The deliveries status
    event uses the last governed timestamp (shipping date) — no invented time.
    """
    first = order_rows[0]

    # ORDER_CREATED: nested order-level aggregate digest.
    order_created = {
        "event_type": "ORDER_CREATED",
        "event_timestamp": order_creation_canonical,
        "payload_digest": order_aggregate_digest(aggregate),
    }

    # SHIPMENT_RECORDED: digest over order identity + canonical shipment time.
    shipment_payload = {
        "order_id": aggregate["order_id"],
        "shipment_canonical": shipment_canonical,
    }
    shipment = {
        "event_type": "SHIPMENT_RECORDED",
        "event_timestamp": shipment_canonical,
        "payload_digest": sha256_hex(shipment_payload),
    }

    # DELIVERY_STATUS_RECORDED: observed delivery status (and order status, if
    # present and non-empty) inside the payload. Timestamp == shipment canonical
    # (last governed timestamp); frozen sequence keeps time ordering.
    delivery_payload: dict[str, Any] = {
        "order_id": aggregate["order_id"],
        "delivery_status": _observed_or_sentinel(first, DELIVERY_STATUS_COLUMN),
    }
    order_status = first.get(ORDER_STATUS_COLUMN)
    if order_status is not None and str(order_status).strip():
        delivery_payload["order_status"] = str(order_status).strip()
    delivery = {
        "event_type": "DELIVERY_STATUS_RECORDED",
        "event_timestamp": shipment_canonical,
        "payload_digest": sha256_hex(delivery_payload),
    }

    return [order_created, shipment, delivery]


def event_payload_digests(
    order_rows: list[Mapping[str, Any]],
    *,
    aggregate: Mapping[str, Any],
    order_creation_canonical: str,
    shipment_canonical: str,
) -> dict[str, str]:
    """Return ``{event_type: payload_digest}`` for the three V1.1-C events."""
    events = build_mapping_events(
        order_rows,
        aggregate=aggregate,
        order_creation_canonical=order_creation_canonical,
        shipment_canonical=shipment_canonical,
    )
    return {event["event_type"]: event["payload_digest"] for event in events}


def canonical_form_from_row(row: Mapping[str, Any]) -> tuple[str, str]:
    """Return ``(order_creation_canonical, shipment_canonical)`` from a row."""
    return (
        canonical_timestamp(row["order date (DateOrders)"]),
        canonical_timestamp(row["shipping date (DateOrders)"]),
    )